### ISSUE TITLE
No such module 'AdpPushClient'

### ISSUE THREAD

**Issue by aminjalalian** [chabokpush/chabok-client-ios#12]
In all pages works except NotificationService.swift
<img width="986" alt="screen shot 1397-05-25 at 16 20 55" src="https://user-images.githubusercontent.com/26254008/44206965-baf7a100-a170-11e8-8ada-36c596fb8737.png">

**Comment by Husseinhj** [comment]
Did you added the Chabok framework pod to your target (`NotificationExtentionService`)?

> `Note : `For each target, You should add your targets in pod. So your `NotificationExtentionService` need to added in **pod** to have access the Chabok framework.

```ruby
target 'YourTarget' do
  use_frameworks!

  pod 'ChabokPush'
  
end
```

**Comment by aminjalalian** [comment]
yes
I use it in AppDelegate.swift and it works
except this page

**Comment by Husseinhj** [comment]
In your pod file you should add your pods also for your other targets.
It’s work on your AppDelegate because of you by default add your app target in pod file, For use Pod libraries in your other target such as watch service or notification service you should add POD Target block config for your other target.
An example for simple project with notification service your pod file should contain these values:


```ruby
platform :ios, '9.0'

target 'YOUR_APP_TARGET' do
    use_frameworks!

    pod 'ChabokPush'

end


target 'NotificationExtentionServiceTarget' do
    use_frameworks!

    pod 'ChabokPush'
    
end

```

This pod config will linking your pods for each target of your project.

**Comment by aminjalalian** [comment]
It worked
Thanks
